### ISSUE TITLE
Query failing

### ISSUE THREAD

**Issue by maxglycine** [legumeinfo/mine-issues#157] opened 2024-04-15 19:52 UTC
This glycine mine query is failing.  I tried this morning and again this afternoon.

https://mines.legumeinfo.org/glycinemine/keywordSearchResults.do?searchTerm=%22seed+oil%22&searchSubmit=GO
![Screen Shot 2024-04-15 at 2 50 45 PM](https://github.com/legumeinfo/mine-issues/assets/14073707/f9e45786-e992-4f4d-a5f8-e6de1e319e89)@adf @StevenCannon-USDA @jd-campbell 

It seems the double quotes (") are the issue.  It did work a while ago, the instructions say you can use it to query with a phrase, but it fails.  So does using a singel quote (').

**Comment by adf-ncgr** [comment] 2024-04-15 20:09
Thanks @maxglycine, not sure what to make of that but we can look into it. Glad that it still works without quotes, in any case.

**Comment by adf-ncgr** [comment] 2024-04-15 20:26
Interestingly, the error is not reported when double quotes are used on some phrase which does not actually return any matches: https://mines.legumeinfo.org/glycinemine/keywordSearchResults.do?searchTerm=%22do+not+return+results%22&searchSubmit=Search

**Comment by adf-ncgr** [comment] 2024-04-15 20:27
And also OK with some that do:
https://mines.legumeinfo.org/glycinemine/keywordSearchResults.do?searchTerm=%22seed+maturation%22&searchSubmit=Search
So what's different about 
https://mines.legumeinfo.org/glycinemine/keywordSearchResults.do?searchTerm=%22seed+oil%22&searchSubmit=Search
??

**Comment by adf-ncgr** [comment] 2024-04-15 20:35
the quotes seem to have been a red herring; this fails: 
https://mines.legumeinfo.org/glycinemine/keywordSearchResults.do?searchTerm=oil&searchSubmit=Search 
although this is fine:
https://mines.legumeinfo.org/glycinemine/keywordSearchResults.do?searchTerm=seed&searchSubmit=Search
so it is likely some issue caused by a result. FWIW, the relevant part of the stack trace is:
`java.lang.NullPointerException: object must not be null.at org.intermine.api.searchengine.KeywordSearchResultContainer.<init>(KeywordSearchResultContainer.java:54)at org.intermine.api.searchengine.solr.SolrKeywordSearchHandler.getSearchHits(SolrKeywordSearchHandler.java:183)at org.intermine.api.searchengine.solr.SolrKeywordSearchHandler.doKeywordSearch(SolrKeywordSearchHandler.java:82)at org.intermine.web.struts.KeywordSearchResultsController.execute(KeywordSearchResultsController.java:129)at `

suggesting that it may be something in the Intermine ObjectStore.

**Comment by maxglycine** [comment] 2024-04-15 20:42
Remember, the query with the double quotes WAS working, but suddenly stopped.  Has there been a recent config change or mine version upgrade?  Maybe the server all of a sudden does not like double quotes?

**Comment by adf-ncgr** [comment] 2024-04-15 20:55
nah, based on the code throwing that error I think it is some specific item in the result set that if it happens to be in the page of results being returned triggers the exception. For example skipping the first page of results but using the query you wanted to make works fine:
https://mines.legumeinfo.org/glycinemine/keywordSearchResults.do?searchTerm=%22seed%20oil%22&searchBag=&searchOffset=100

**Comment by adf-ncgr** [comment] 2024-04-29 19:00
fixed by rebuilding keyword search indices along with some new genome data

**Closed as completed by adf-ncgr** 2024-04-29 19:00 UTC
