### ISSUE TITLE
cowpeamine should use IT97K-499-35.gnm1.ann2 annotations rather than ann1

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/mine-issues#25] opened 2021-06-06 18:38 UTC
for some reason they did not seem to be in the datastore, just the ann1 were there. Not sure we need to support both, but probably ought to at least have the latest and greatest. They are there now, although you may need to run the pathway assignments (possibly those should be rerun on anything that gets the gfa files updated too, although the impact should be pretty minimal)

**Comment by sammyjava** [comment] 2021-06-07 20:46
This is because I cannot merge genetic markers from a single secondary identifier from genetic data with two different sequence features. I'll close this now because I've fired up a new issue about solving this, which, when implemented, will allow me to load arbitrarily many genomes for a given strain.

**Comment by adf-ncgr** [comment] 2021-06-07 20:49
well, this is really about having a new annotation on the same version of the genome (gnm1). What I meant was that we probably don't need to have both the ann1 gene models and the ann2 gene models in place together, but I don't see why switching to the new gene models has any bearing on the marker mapping to the same version of the genome?

**Comment by sammyjava** [comment] 2021-06-07 20:53
Ahhh yeah sorry, I was thinking gnm version. I'll switch to ann2 in the next build.

**Comment by sammyjava** [comment] 2021-06-08 15:27
I'm closing stuff that is fixed even if it's not visible in production. The problem is fixed and tested. Please do not reopen, no further action is required on my part.

**Closed as completed by sammyjava** 2021-06-08 15:27 UTC
